version: '3.1'
services:
  odoo-web:
    image: odoo:17.0
    depends_on:
      - oddo-db
    ports:
      - "${PORT}:8069"
    environment:
    - HOST=odoo-db
    - USER=${WEBUSER}
    - PASSWORD=${WEBPASSWORD}
    volumes:
    - odoo-web-data:/var/lib/odoo
    - ./config:/etc/odoo
    - ./addons:/mnt/extra-addons

  odoo-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_USER=${DBUSER}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
